name: Run Tests on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (Uniform)
      run: pytest tests/test-uniform.py --maxfail=5 --disable-warnings

    - name: Run Tests (Choice)
      run: pytest tests/test-choice.py --maxfail=5 --disable-warnings

    - name: Run Tests (Rand)
      run: pytest tests/test-rand.py --maxfail=5 --disable-warnings

    - name: Run Tests (Randrange)
      run: pytest tests/test-randrange.py --maxfail=5 --disable-warnings